# Generated by Django 5.1.3 on 2025-01-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('altura', models.DecimalField(decimal_places=1, max_digits=2)),
                ('largura', models.DecimalField(decimal_places=1, max_digits=2)),
                ('profundidade', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fator_empilhamento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('altura', models.DecimalField(decimal_places=1, max_digits=2)),
                ('largura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('profundidade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('id_gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qnt_disponivel', models.IntegerField()),
                ('qnt_vendas', models.IntegerField()),
                ('ultima_venda', models.DateField(auto_now=True)),
                ('id_dados_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.dadosproduto')),
                ('id_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja')),
            ],
        ),
    ]
