# Generated by Django 5.1.3 on 2025-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='id_gerente',
            field=models.IntegerField(default=0),
        ),
    ]
