# Generated by Django 5.1.3 on 2025-01-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_loja_id_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosproduto',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosproduto',
            name='largura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosproduto',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadosproduto',
            name='profundidade',
            field=models.IntegerField(),
        ),
    ]
