# Generated by Django 5.1.3 on 2025-01-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_loja_id_gerente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='altura',
        ),
        migrations.AddField(
            model_name='loja',
            name='distancia',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
