# Generated by Django 5.1.3 on 2025-01-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_loja_altura_loja_distancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='id_gerente',
            new_name='gerente',
        ),
    ]
