# Generated by Django 5.1.3 on 2025-01-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_id_gerente_loja_gerente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='distancia',
        ),
    ]
