# Generated by Django 5.1.3 on 2025-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_remove_loja_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tipo_organizacao',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
