# Generated by Django 5.1.3 on 2025-01-30 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_loja_tipo_organizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatorProdutoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_produto_mes', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fator', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.produtoloja')),
            ],
        ),
    ]
