# Generated by Django 5.1.3 on 2025-02-03 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_fatorprodutomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='tipo_organizacao',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
