# Generated by Django 5.1.3 on 2025-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_remove_produtoloja_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produtoloja',
            name='qnt_disponivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produtoloja',
            name='qnt_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
