# Generated by Django 5.1.3 on 2025-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id_loja',
            field=models.IntegerField(default=0),
        ),
    ]
