# Generated by Django 5.1.3 on 2025-01-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_funcionario_id_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.funcionario',),
        ),
    ]
