# Generated by Django 5.1.3 on 2025-01-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gerente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gerente',
        ),
    ]
